# Practical session 3 - Practice with numpy

Course: [SDIA-Python](https://github.com/guilgautier/sdia-python)

Date: 10/06/2021

Instructor: [Guillaume Gautier](https://guilgautier.github.io/)

Students (pair):
- [Student 1]([link](https://github.com/username1))
- [Student 2]([link](https://github.com/username2))

In [2]:
%load_ext autoreload
%autoreload 2

import numpy as np
from lab2.utils import get_random_number_generator

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [3]:
my_array = np.array([0])
print(type(my_array))
dir(np.ndarray)

<class 'numpy.ndarray'>


['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

Propose at leat 2 ways to create an integer vector of size 100 made of 1s

In [11]:
vect = np.ones(100)
vect_bis = np.full(100,1)

100


Create a vector with values ranging from 10 to 49

In [12]:
vect = np.arange(10,50)
print(vect)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Propose a way to construct the vector $(0.0, 0.2, 0.4, 0.6, 0.8)$

In [27]:
vect = np.linspace(0,0.8,5)
vect = np.arange(0,1,0.2)
print(vect)

[0.  0.2 0.4 0.6 0.8]


Convert a float array into an integer array in place

In [26]:
print(id(vect))
vect = vect.astype(int)
print(id(vect))
print(vect)

2549029119152
2549029119536
[0 0 0 0 0]


Given a boolean array

- return the indices where 
- negate the array inplace? 

In [45]:
vect =np.array([False,False,True,False,True])
print(np.argwhere (vect))

[[2]
 [4]]


In [46]:
print(id(vect))
np.logical_not(vect, out=vect)
print(id(vect))
print(vect)

2549029295760
2549029295760
[ True  True False  True False]


Given 2 vectors $u, v$, propose at least

- 2 ways to compute the inner product $v^{\top} u$ (here they must have the same size)
- 2 ways to compute the outer product matrix $u v^{\top}$
- 2 ways to compute the outer sum matrix "$M = u + v^{\top}$", where $M_{ij} = u_i + v_j$

In [67]:
u = np.arange(1,5)
v = np.arange(5,13,2)
product = np.dot(v.T,u)
print(np.inner(u,v))

90


In [68]:
print(np.outer(u,v))


[[ 5  7  9 11]
 [10 14 18 22]
 [15 21 27 33]
 [20 28 36 44]]


In [69]:

mat_u = np.repeat(u,4,axis = 0).reshape(4,4)
mat_v = np.repeat(v,4,axis = 0).reshape(4,4).T
print(mat_u + mat_v)


[[ 6  8 10 12]
 [ 7  9 11 13]
 [ 8 10 12 14]
 [ 9 11 13 15]]


In [71]:
print(np.add.outer(u,v))

[[ 6  8 10 12]
 [ 7  9 11 13]
 [ 8 10 12 14]
 [ 9 11 13 15]]


Given the following matrix

$$
M = 
\begin{pmatrix}
    0 & 1 & 2 \\
    3 & 4 & 5 \\
    6 & 7 & 8 \\
\end{pmatrix}
$$

- Create $M$ using as a list of lists and access the element in the middle
- Propose at least 2 ways to create $M$ using numpy and access the element in the middle
- Swap its first and second row
- Propose at least 3 ways to extract the submatrix $\begin{pmatrix}4 & 5 \\7 & 8 \\\end{pmatrix}$
- Propose at least 2 ways to extract the diagonal of $M$
- Propose at least 2 ways to compute $M^3$
- Compute $v^{\top} M$, resp. $M N$ for a vector, resp. a matrix of your choice. 
- Propose 2 ways to "vectorize" the matrix, i.e., transform it into
  - $(0, 1, 2, 3, 4, 5, 6, 7, 8)$
  - $(0, 3, 6, 1, 4, 7, 2, 5, 8)$
- Consider $v = (1, 2 , 3)$, compute the
  - row-wise multiplication of $M$ by $v$ ($M_{i\cdot}$ is multiplied by $v_i$)
  - column-wise multiplication of $M$ by $v$ ($M_{\cdot j}$ is multiplied by $v_i$)

Write a function `is_symmetric` that checks whether a given n x n matrix is symmetric, and provide an example

## Random

REQUIREMENT: USE THE FUNCTION `get_random_number_generator` as previously used in Lab 2.

Consider the Bernoulli(0.4) distribution

- Propose at least 2 ways to generate n=1000 samples from it
- Compute the empirical mean and variance

Consider a random matrix of size $50 \times 100$, filled with i.i.d. standard Gaussian variables, compute

- the absolute value of each entry
- the sum of each row
- the sum of each colomn 
- the (euclidean) norm of each row
- the (euclidean) norm of each column