# Practical session 3 - Practice with numpy

Course: [SDIA-Python](https://github.com/guilgautier/sdia-python)

Date: 10/06/2021

Instructor: [Guillaume Gautier](https://guilgautier.github.io/)

Students (pair):
- [Student 1]([link](https://github.com/username1))
- [Student 2]([link](https://github.com/username2))

In [17]:
%load_ext autoreload
%autoreload 2

import numpy as np
from lab2.utils import get_random_number_generator

In [18]:
my_array = np.array([0])
print(type(my_array))
dir(np.ndarray)

<class 'numpy.ndarray'>


['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

Propose at leat 2 ways to create an integer vector of size 100 made of 1s

In [19]:
vector1 = np.array([1]*100)
vector2 = np.ones((1,100))
vector1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

Create a vector with values ranging from 10 to 49

In [20]:
vector_range = np.arange(10,49+1)
vector_range

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Propose a way to construct the vector $(0.0, 0.2, 0.4, 0.6, 0.8)$

In [21]:
np.array([0.0, 0.2,0.4,0.6,0.8])


array([0. , 0.2, 0.4, 0.6, 0.8])

In [22]:
V = np.arange(0, 100, step=20)/100
V

array([0. , 0.2, 0.4, 0.6, 0.8])

Convert a float array into an integer array in place

In [23]:
V = np.array([1.0, 2.0, 3.0, 4.0])
id(V)

2314938737840

In [24]:
V = V.astype(int, copy=False)
V.dtype

dtype('int32')

Given a boolean array

- return the indices where True
- negate the array inplace? 

In [25]:
bool_arr = np.array([True, False, True, True, True, False])
np.argwhere(bool_arr == True)[:,0]

array([0, 2, 3, 4], dtype=int64)

In [26]:
bool_arr_neg = np.where(bool_arr==True, False, True)
bool_arr_neg

array([False,  True, False, False, False,  True])

Given 2 vectors $u, v$, propose at least

- 2 ways to compute the inner product $v^{\top} u$ (here they must have the same size)
- 2 ways to compute the outer product matrix $u v^{\top}$
- 2 ways to compute the outer sum matrix "$M = u + v^{\top}$", where $M_{ij} = u_i + v_j$

In [27]:
u = np.array([1, 2, 4, 1])
v = np.array([0, 5, 3, 1])

In [28]:
# Inner Product

prod1 = np.dot(v.T,u)
prod2 = np.inner(u,v)
prod2

23

In [29]:
outer1 = np.outer(u,v)

Given the following matrix

$$
M = 
\begin{pmatrix}
    0 & 1 & 2 \\
    3 & 4 & 5 \\
    6 & 7 & 8 \\
\end{pmatrix}
$$

- Create $M$ using as a list of lists and access the element in the middle
- Propose at least 2 ways to create $M$ using numpy and access the element in the middle
- Swap its first and second row
- Propose at least 3 ways to extract the submatrix $\begin{pmatrix}4 & 5 \\7 & 8 \\\end{pmatrix}$
- Propose at least 2 ways to extract the diagonal of $M$
- Propose at least 2 ways to compute $M^3$
- Compute $v^{\top} M$, resp. $M N$ for a vector, resp. a matrix of your choice. 
- Propose 2 ways to "vectorize" the matrix, i.e., transform it into
  - $(0, 1, 2, 3, 4, 5, 6, 7, 8)$
  - $(0, 3, 6, 1, 4, 7, 2, 5, 8)$
- Consider $v = (1, 2 , 3)$, compute the
  - row-wise multiplication of $M$ by $v$ ($M_{i\cdot}$ is multiplied by $v_i$)
  - column-wise multiplication of $M$ by $v$ ($M_{\cdot j}$ is multiplied by $v_i$)

In [30]:
M = [[0,1,2],
     [3,4,5],
     [6,7,8]]
M[1][1]

4

In [31]:
M = np.array(M)
M = np.arange(0,9).reshape((3,3))
M



array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
# Swapping first 2 rows
M[[0, 1]] = M[[1, 0]]
M

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [33]:
# Extract submatrix
M = np.arange(0,9).reshape((3,3))
sub1 = M[1:,1:]

Write a function `is_symmetric` that checks whether a given n x n matrix is symmetric, and provide an example

## Random

REQUIREMENT: USE THE FUNCTION `get_random_number_generator` as previously used in Lab 2.

In [34]:
from lab2.utils import get_random_number_generator

In [35]:
rng  = get_random_number_generator(12345)

Consider the Bernoulli(0.4) distribution

- Propose at least 2 ways to generate n=1000 samples from it
- Compute the empirical mean and variance

In [65]:
bernoulli_vecteur = rng.binomial(size=1000, n=1, p= 0.4)
print('Moyenne empirique :' + str(bernoulli_vecteur.mean()))
print('Variance empirique :' + str(bernoulli_vecteur.std()**2))

Moyenne empirique :0.376
Variance empirique :0.23462400000000005


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

Consider a random matrix of size $50 \times 100$, filled with i.i.d. standard Gaussian variables, compute

- the absolute value of each entry
- the sum of each row
- the sum of each colomn 
- the (euclidean) norm of each row
- the (euclidean) norm of each column

In [67]:
gaussian_matrix = rng.standard_normal(size=((50,100)))

array([[-1.86526045e+00, -2.17434331e-01, -1.34278037e+00, ...,
        -1.37611535e+00, -2.82897921e-01,  5.64047947e-02],
       [-1.16277153e+00,  1.78556675e+00,  5.40597872e-01, ...,
         1.02319527e+00,  9.22353232e-01, -9.24962917e-01],
       [-1.06765327e-01,  5.23831335e-02,  7.25009816e-01, ...,
        -2.49741923e-01, -1.05543269e+00,  2.48890951e-01],
       ...,
       [ 2.00426452e-01, -6.23346031e-01,  2.69054627e+00, ...,
         2.57374208e-02,  4.80371885e-01, -1.51881514e+00],
       [ 4.14720067e-01,  4.62528224e-01,  1.10464697e+00, ...,
        -1.29031585e+00, -2.65583403e-03, -2.13930557e-01],
       [ 4.64529271e-01,  1.32672055e+00, -8.03758184e-01, ...,
         7.50837942e-01, -5.79972743e-01, -8.91680151e-01]])

In [68]:
# Absolute value of each entry

gaussian_matrix_abs = np.abs(gaussian_matrix)

array([[1.86526045e+00, 2.17434331e-01, 1.34278037e+00, ...,
        1.37611535e+00, 2.82897921e-01, 5.64047947e-02],
       [1.16277153e+00, 1.78556675e+00, 5.40597872e-01, ...,
        1.02319527e+00, 9.22353232e-01, 9.24962917e-01],
       [1.06765327e-01, 5.23831335e-02, 7.25009816e-01, ...,
        2.49741923e-01, 1.05543269e+00, 2.48890951e-01],
       ...,
       [2.00426452e-01, 6.23346031e-01, 2.69054627e+00, ...,
        2.57374208e-02, 4.80371885e-01, 1.51881514e+00],
       [4.14720067e-01, 4.62528224e-01, 1.10464697e+00, ...,
        1.29031585e+00, 2.65583403e-03, 2.13930557e-01],
       [4.64529271e-01, 1.32672055e+00, 8.03758184e-01, ...,
        7.50837942e-01, 5.79972743e-01, 8.91680151e-01]])

In [69]:
# sum of each row

np.sum(gaussian_matrix, axis = 0)

array([ -3.00707526,   4.4561637 ,   1.68422022,  -1.972696  ,
        -1.62165023,   7.50420451,  12.54940219,   2.44978792,
        -6.10020837,   0.95679879,  10.21700259,  10.02867782,
         2.79082113,   5.75694722,   9.40107998,  -2.45406322,
        -9.29295166,  -3.07897693,  -3.7526096 ,  -2.74541806,
         5.09078095, -10.30953247,   2.08166008,  -7.67368233,
         3.12968574,  -4.48434146, -11.03588772,   6.83984536,
         3.34835929,  -0.7354625 ,   7.31809901,   6.01139114,
         2.45309644,   7.07192409,  -9.21548559,   2.59508039,
        -3.52709   ,   3.1926959 ,   0.76540706,  -1.60774329,
        -2.78275097,   6.12017678,  -5.16664671,  -4.17121175,
         3.02784449,  10.60454488,  -1.29256206,  -1.81687177,
        -4.33980405,  -6.41209654,   8.22987243,  -3.31593844,
        -2.50183834,  -5.35589063,  -8.88827023,  -1.34876515,
        -2.70992073,   1.13024429,  -0.24848387,  15.06627585,
         6.72708572,   6.22651544, -23.53650984,   4.33

In [ ]:
# sum of each column

np.sum(gaussian_matrix, axis = 0)

In [72]:
# Euclidian norm of each row

np.linalg.norm(gaussian_matrix, axis=1)

50

In [73]:
# Euclidian norm of each column

np.linalg.norm(gaussian_matrix, axis=0)

100