# Practical session 3 - Practice with numpy

Course: [SDIA-Python](https://github.com/guilgautier/sdia-python)

Date: 10/06/2021

Instructor: [Guillaume Gautier](https://guilgautier.github.io/)

Students (pair):
- [Student 1]([link](https://github.com/username1))
- [Student 2]([link](https://github.com/username2))

In [3]:
%load_ext autoreload
%autoreload 2

import numpy as np
from sdia_python.lab2.utils import get_random_number_generator

In [4]:
my_array = np.array([0])
print(type(my_array))
dir(np.ndarray)

<class 'numpy.ndarray'>


['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

Propose at leat 2 ways to create an integer vector of size 100 made of 1s

In [5]:
vector1 = np.array([1]*100)
vector2 = np.ones((1,100))
vector1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

Create a vector with values ranging from 10 to 49

In [6]:
vector_range = np.arange(10,49+1)
vector_range

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Propose a way to construct the vector $(0.0, 0.2, 0.4, 0.6, 0.8)$

In [7]:
np.array([0.0, 0.2,0.4,0.6,0.8])


array([0. , 0.2, 0.4, 0.6, 0.8])

In [8]:
V = np.arange(0, 100, step=20)/100
V

array([0. , 0.2, 0.4, 0.6, 0.8])

Convert a float array into an integer array in place

In [9]:
V = np.array([1.0, 2.0, 3.0, 4.0])
id(V)

2119433620816

In [10]:
V = V.astype(int, copy=False)
V.dtype

dtype('int32')

Given a boolean array

- return the indices where True
- negate the array inplace? 

In [11]:
bool_arr = np.array([True, False, True, True, True, False])
np.argwhere(bool_arr == True)[:,0]

array([0, 2, 3, 4], dtype=int64)

In [12]:
bool_arr_neg = np.where(bool_arr==True, False, True)
bool_arr_neg

array([False,  True, False, False, False,  True])

Given 2 vectors $u, v$, propose at least

- 2 ways to compute the inner product $v^{\top} u$ (here they must have the same size)
- 2 ways to compute the outer product matrix $u v^{\top}$
- 2 ways to compute the outer sum matrix "$M = u + v^{\top}$", where $M_{ij} = u_i + v_j$

In [13]:
u = np.array([1, 2, 4, 1])
v = np.array([0, 5, 3, 1])

In [14]:
# Inner Product

prod1 = np.dot(v.T,u)
prod2 = np.inner(u,v)
prod2

23

In [15]:
outer1 = np.outer(u,v)

Given the following matrix

$$
M = 
\begin{pmatrix}
    0 & 1 & 2 \\
    3 & 4 & 5 \\
    6 & 7 & 8 \\
\end{pmatrix}
$$

- Create $M$ using as a list of lists and access the element in the middle
- Propose at least 2 ways to create $M$ using numpy and access the element in the middle
- Swap its first and second row
- Propose at least 3 ways to extract the submatrix $\begin{pmatrix}4 & 5 \\7 & 8 \\\end{pmatrix}$
- Propose at least 2 ways to extract the diagonal of $M$
- Propose at least 2 ways to compute $M^3$
- Compute $v^{\top} M$, resp. $M N$ for a vector, resp. a matrix of your choice. 
- Propose 2 ways to "vectorize" the matrix, i.e., transform it into
  - $(0, 1, 2, 3, 4, 5, 6, 7, 8)$
  - $(0, 3, 6, 1, 4, 7, 2, 5, 8)$
- Consider $v = (1, 2 , 3)$, compute the
  - row-wise multiplication of $M$ by $v$ ($M_{i\cdot}$ is multiplied by $v_i$)
  - column-wise multiplication of $M$ by $v$ ($M_{\cdot j}$ is multiplied by $v_i$)

In [16]:
M = [[0,1,2],
     [3,4,5],
     [6,7,8]]
M[1][1]

4

In [17]:
M = np.array(M)
M = np.arange(0,9).reshape((3,3))
M



array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
# Swapping first 2 rows
M[[0, 1]] = M[[1, 0]]
M

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [19]:
# Extract submatrix
M = np.arange(0,9).reshape((3,3))
sub1 = M[1:,1:]
sub2 = M[[1,2]].T[[1,2]].T
sub3 = M[np.logical_and(M>3,M!=6)].reshape((2,2))

In [ ]:
# Extract diagonal
np.diag(M)
M.diagonal()

In [30]:
# Compute M^3

product_3 = np.dot(np.dot(M,M),M)
product_3 = np.linalg.matrix_power(M, 3)
product_3

array([[ 180,  234,  288],
       [ 558,  720,  882],
       [ 936, 1206, 1476]])

In [31]:
v = np.arange(1,4)
np.dot(v,M)

array([24, 30, 36])

In [32]:
N = M.T + np.outer(v,v)
np.dot(M,N)

array([[ 13,  30,  47],
       [ 40, 102, 164],
       [ 67, 174, 281]])

In [33]:
M.ravel()
M.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
M.T.ravel()
M.T.flatten()

array([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [35]:
v = np.arange(1,4)
np.multiply(v,M.T).T

array([[ 0,  1,  2],
       [ 6,  8, 10],
       [18, 21, 24]])

In [36]:
v = np.arange(1,4)
np.multiply(v,M)

array([[ 0,  2,  6],
       [ 3,  8, 15],
       [ 6, 14, 24]])

Write a function `is_symmetric` that checks whether a given n x n matrix is symmetric, and provide an example

In [20]:
M = np.arange(0,9).reshape((3,3))

def is_symmetric(M):
    assert M.shape[0] == M.shape[1] and len(np.shape(M)) == 2
    return np.all(M.T == M)
print(is_symmetric(M))
print(is_symmetric(np.dot(M.T,M)))

False
True


## Random

REQUIREMENT: USE THE FUNCTION `get_random_number_generator` as previously used in Lab 2.

In [21]:
from sdia_python.lab2.utils import get_random_number_generator

In [22]:
rng  = get_random_number_generator(12345)

Consider the Bernoulli(0.4) distribution

- Propose at least 2 ways to generate n=1000 samples from it
- Compute the empirical mean and variance

In [23]:
bernoulli_vecteur = rng.binomial(size=1000, n=1, p= 0.4)
print('Moyenne empirique :' + str(bernoulli_vecteur.mean()))
print('Variance empirique :' + str(bernoulli_vecteur.std()**2))

Moyenne empirique :0.38
Variance empirique :0.23560000000000006


Consider a random matrix of size $50 \times 100$, filled with i.i.d. standard Gaussian variables, compute

- the absolute value of each entry
- the sum of each row
- the sum of each colomn 
- the (euclidean) norm of each row
- the (euclidean) norm of each column

In [24]:
gaussian_matrix = rng.standard_normal(size=((50,100)))

In [25]:
# Absolute value of each entry

gaussian_matrix_abs = np.abs(gaussian_matrix)

In [26]:
# sum of each row

np.sum(gaussian_matrix, axis = 0)

array([ 10.1668517 ,   9.71761874,   1.30806307,   5.85512659,
        -8.36970104,  -6.29317955,   4.52777165,   8.59737463,
        -2.23673678,  -4.38207594,  -8.79147924,   4.09750423,
         6.50177066,   0.97617598,  -2.68295368,  -2.18239086,
        -7.47997719,  -3.53821856,   4.27884645,   4.48447616,
         2.52343957,  -3.00707526,   4.4561637 ,   1.68422022,
        -1.972696  ,  -1.62165023,   7.50420451,  12.54940219,
         2.44978792,  -6.10020837,   0.95679879,  10.21700259,
        10.02867782,   2.79082113,   5.75694722,   9.40107998,
        -2.45406322,  -9.29295166,  -3.07897693,  -3.7526096 ,
        -2.74541806,   5.09078095, -10.30953247,   2.08166008,
        -7.67368233,   3.12968574,  -4.48434146, -11.03588772,
         6.83984536,   3.34835929,  -0.7354625 ,   7.31809901,
         6.01139114,   2.45309644,   7.07192409,  -9.21548559,
         2.59508039,  -3.52709   ,   3.1926959 ,   0.76540706,
        -1.60774329,  -2.78275097,   6.12017678,  -5.16

In [27]:
# sum of each column

np.sum(gaussian_matrix, axis = 0)

array([ 10.1668517 ,   9.71761874,   1.30806307,   5.85512659,
        -8.36970104,  -6.29317955,   4.52777165,   8.59737463,
        -2.23673678,  -4.38207594,  -8.79147924,   4.09750423,
         6.50177066,   0.97617598,  -2.68295368,  -2.18239086,
        -7.47997719,  -3.53821856,   4.27884645,   4.48447616,
         2.52343957,  -3.00707526,   4.4561637 ,   1.68422022,
        -1.972696  ,  -1.62165023,   7.50420451,  12.54940219,
         2.44978792,  -6.10020837,   0.95679879,  10.21700259,
        10.02867782,   2.79082113,   5.75694722,   9.40107998,
        -2.45406322,  -9.29295166,  -3.07897693,  -3.7526096 ,
        -2.74541806,   5.09078095, -10.30953247,   2.08166008,
        -7.67368233,   3.12968574,  -4.48434146, -11.03588772,
         6.83984536,   3.34835929,  -0.7354625 ,   7.31809901,
         6.01139114,   2.45309644,   7.07192409,  -9.21548559,
         2.59508039,  -3.52709   ,   3.1926959 ,   0.76540706,
        -1.60774329,  -2.78275097,   6.12017678,  -5.16

In [28]:
# Euclidian norm of each row

np.linalg.norm(gaussian_matrix, axis=1)

array([10.23738215,  9.7896519 , 10.66212665, 10.84060691,  9.97163826,
       10.14451937,  9.57549885,  9.39155066,  9.92436839, 10.56515226,
        9.78287489,  9.99748559,  9.24751519, 11.19438283, 10.23960282,
       11.29213553,  9.95005485,  8.7319822 , 10.02792383,  9.57037553,
        9.87376312,  9.97718424, 10.46619171,  9.64822723, 10.24018225,
       10.13187877, 10.3727857 ,  8.91769443, 11.37256516,  9.67807373,
        9.68206814,  9.20979901, 11.2504958 , 10.04211369,  9.62841352,
       10.11920325, 12.07412954,  9.99149241, 10.34254612, 10.3440063 ,
        9.6435792 , 10.00318232,  9.88945353,  9.67525552, 10.02247881,
        9.97254095,  9.97414744, 10.46114091,  9.49625293, 10.49780726])

In [29]:
# Euclidian norm of each column

np.linalg.norm(gaussian_matrix, axis=0)

array([7.84590824, 6.15487685, 6.69974549, 7.32977792, 5.6299983 ,
       7.85986684, 6.58094203, 5.60120238, 7.54612609, 7.20865494,
       6.51470934, 6.68268692, 7.54323428, 6.81286313, 6.9142118 ,
       7.52624863, 8.00477507, 7.30251209, 7.44109681, 6.93521575,
       7.38666549, 6.8219872 , 7.55112175, 7.64357189, 7.93666946,
       6.56427476, 6.79265212, 7.63550501, 7.57878964, 7.51912607,
       9.31874992, 7.29256025, 8.03841047, 6.09086253, 7.16030185,
       8.36758765, 7.66130198, 7.23015192, 7.01494867, 6.1782841 ,
       8.04132156, 6.37686286, 7.49280234, 7.47862956, 7.96071296,
       6.22420193, 7.14992013, 7.10241282, 6.80485945, 6.68329776,
       6.04967503, 8.35728121, 7.61961805, 6.10871271, 7.38223514,
       6.74345115, 7.58942049, 7.52731295, 6.83227608, 7.60616336,
       7.12662784, 7.84006242, 7.74437752, 7.63690215, 7.60104035,
       6.58125413, 8.09654984, 7.01155218, 7.1501123 , 7.45457144,
       7.24671713, 6.62969291, 7.91500006, 6.88048759, 5.13218